name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type YES to confirm destroy'
        required: true
        default: 'NO'

jobs:
  terraform:
    if: inputs.confirmation == 'YES'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Create SSH Key File
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.STRAPI_EC2_KEY }}" > /home/runner/.ssh/strapi-key.pem
          chmod 600 /home/runner/.ssh/strapi-key.pem
          ls -al /home/runner/.ssh  # Verify permissions and existence

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.GOWTHAM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GOWTHAM_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform  # Update this path if necessary

      - name: Destroy Terraform
        run: terraform destroy -auto-approve -var="private_key_path=/home/runner/.ssh/Ashwanikey.pem"
        working-directory: ./terraform  # Update this path if necessary
